#!/system/bin/sh

RUN_EVERY=86400

system information:
vendor   : $( getprop ro.product.brand )
model    : $( getprop ro.product.model )
ROM      : $( getprop ro.build.display.id )

running the script...
start at:
$( date +"%m-%d-%Y %H:%M:%S" )
==========================" | tee -a $LOG_FILE;


# cleaner
busybox rm -f /data/anr/*.*
busybox rm -f /data/cache/*.*
busybox rm -f /data/log/*.*
busybox rm -f /data/local/tmp/*.*
busybox rm -f /data/last_alog/*
busybox rm -f /data/last_kmsg/*
busybox rm -f /data/mlog/*
busybox rm -f /data/tombstones/*
busybox rm -f /data/system/dropbox/*
chmod 400 /data/system/dropbox
busybox rm -f /data/system/usagestats/*
busybox chmod 400 /data/system/usagestats

export sampling_rate=10000
export up_threshold=80

echo "memory cleaner--------[OK]" | tee -a $LOG_FILE;

if [ -e /data/anr/*.* ]; then
  echo "-anr not cleaned" | tee -a $LOG_FILE; else
  echo "-anr cleaned" | tee -a $LOG_FILE
fi;
if [ -e /data/local/tmp/*.* ]; then
  echo "-local/tmp not cleaned" | tee -a $LOG_FILE; else
  echo "-local/tmp cleaned" | tee -a $LOG_FILE
fi;
if [ -e /data/cache/*.* ]; then
  echo "-cache not cleaned" | tee -a $LOG_FILE; else
  echo "-cache cleaned" | tee -a $LOG_FILE
fi;
if [ -e /data/last_log/*.* ]; then
  echo "-log not cleaned" | tee -a $LOG_FILE; else
  echo "-log cleaned" | tee -a $LOG_FILE
fi;
if [ -e /data/tombstones/*.* ]; then
  echo "-tombstones not cleaned" | tee -a $LOG_FILE; else
  echo "-tombstones cleaned" | tee -a $LOG_FILE
fi;
echo "" > /data/sboost/sbkk.log;

exit 0;